apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkzhu-flask-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tkzhu-flask-webapp
  template:
    metadata:
      labels:
        app: tkzhu-flask-webapp
    spec:
      containers:
        - name: tkzhu-flask-webapp
          image: tkzhu66/tkzhu-web-app:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              subPath: config.yaml
              mountPath: /app/config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: webapp-config
